# Documentation:
# https://github.com/trovu/trovu.github.io/wiki/Advanced-settings-&-personal-shortcuts#custom-configuration
namespaces:
- o
- de
- .de
- leo
- github: .
  name: kevang
defaultKeyword: d
language: de
country: de
