# Documentation:
# https://github.com/trovu/trovu.github.io/wiki/Advanced-settings-&-personal-shortcuts#custom-configuration
namespaces:
- o
- de
- dcc
- .de
- .ch
- github: .
defaultKeyword: d
language: de
country: de
