# Documentation:
# https://github.com/trovu/trovu.github.io/wiki/Advanced-settings-&-personal-shortcuts#custom-configuration
namespaces:
- o
- en
- .us
- github: .
  name: my
defaultKeyword: g 
language: de
country: de
