# Documentation:
# https://github.com/trovu/trovu.github.io/wiki/Advanced-settings-&-personal-shortcuts#custom-configuration
namespaces:
- o
- de
- .de
- berlin
- old-o
- dasrecht
- eo
- github: .
defaultKeyword: w
language: de
country: de

# Original:
# namespaces:
# - o
# - en
# - .us
# - github: .
#   name: my
# # defaultKeyword: g 
# language: en
# country: us
